# Generated by Django 3.2.12 on 2022-02-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Item',
        ),
    ]
